#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Ubuntu from USB'  {
recordfail
    load_video
    gfxmode $linux_gfx_mode
    insmod gzio
    insmod part_msdos
    insmod btrfs
    set root='hd1,msdos1'
    linux   /@/boot/vmlinuz-3.11.0-12-generic root=/dev/sdb1 ro rootflags=subvol=@
    initrd  /@/boot/initrd.img-3.11.0-12-generic
}