#!/usr/bin/env bash
#btrfs filesystem for images
if df | grep /var/lib/lxc > /dev/null; then
  echo -n
else
  echo preparing filesystem
  #check for ephemeral device
  DEVICE=/dev/xvdb
  if [ -b ${DEVICE} ]; then
    echo device found
    #and make sure it is btrfs
    if mount | grep ${DEVICE} > /dev/null; then
      umount ${DEVICE}
    fi
    mkfs.btrfs ${DEVICE}
    #scrub away the mount point
    if [ -d /var/lib/lxc ]; then
      rm -rf /var/lib/lxc
    fi
    mkdir -p /var/lib/lxc
    mount ${DEVICE} /var/lib/lxc
    /starphleet/provision/system
  fi
fi
