#!/usr/bin/env bash
#synch over to keep docker from trying to include the vagrant image itself
#into the build -- which is shockingly slow!
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BLUE_BOLD=$(tput setaf 4; tput bold)
NORMAL=$(tput sgr0)

function announce() {
  echo -e "$BLUE_BOLD$*$NORMAL"
}

stop starphleet

#headquarters will go here
mkdir -p /var/starphleet
chmod 0777 /var/starphleet
mkdir -p /var/starphleet/current_orders
mkdir -p /var/starphleet/current_containers
mkdir -p /var/starphleet/private_keys

#put in the system overlay, gets all the files in place
cp -R /starphleet/overlay/* /

rsync -av --exclude-from='/starphleet/.gitignore' --exclude='.git' /starphleet/ /starphleetbuild
docker build -t starphleet /starphleetbuild

ADMIRAL="admiral"
ADMIRAL_HOME="/home/admiral"
useradd ${ADMIRAL} -m -d ${ADMIRAL_HOME}
sudo adduser ${ADMIRAL} sudo

sudo chown ${ADMIRAL} /etc/init/starphleet*
sudo chown ${ADMIRAL} /var/starphleet*
initctl reload-configuration
start starphleet

announce
announce *Welcome to Starphleet*
