#!/usr/bin/env bash
#synch over to keep docker from trying to include the vagrant image itself
#into the build -- which is shockingly slow!

stop starphleet

#headquarters will go here
mkdir -p /var/starphleet
chmod 0777 /var/starphleet

#put in the system overlay, gets all the files in place
cp -R /starphleet/overlay/* /

rm -rf /starphleetbuild
rsync -av --exclude-from='/starphleet/.gitignore' --exclude='.git' /starphleet/ /starphleetbuild
docker build -t starphleet /starphleetbuild

start starphleet
start starphleet_nginx
