#!/usr/bin/env bash
#synch over to keep docker from trying to include the vagrant image itself
#into the build -- which is shockingly slow!

stop starphleet

#headquarters will go here
mkdir -p /var/starphleet
chmod 0777 /var/starphleet

#put in the system overlay, gets all the files in place
cp -R /starphleet/overlay/* /

rsync -av --exclude-from='/starphleet/.gitignore' --exclude='.git' /starphleet/ /starphleetbuild
docker build -t starphleet /starphleetbuild

ADMIRAL="admiral"
ADMIRAL_HOME="/home/admiral"
lastlog | grep ${ADMIRAL} > .admiralexist || true
# If admiral user not found, create the user and add to sudoers
if [ ! -s .admiralexist ]; then
  useradd ${ADMIRAL} -m -d ${ADMIRAL_HOME}
  sudo adduser ${ADMIRAL} sudo
fi

initctl reload-configuration
start starphleet
