#!/usr/bin/env bash
#this script relies on the 'new' ec2 command line, non java version

IMAGE=ami-e457ced4
NAME=starphleet-0.0.3
ZONES="us-east-1 us-west-1 eu-west-1 sa-east-1 ap-northeast-1 ap-southeast-1 ap-southeast-2"

for zone in ${ZONES}
do
  echo $zone
  aws --region ${zone} ec2 describe-images --filters Name=name,Values=${NAME} \
    | jq --raw-output '.Images[].ImageId' \
    | xargs -I % aws --region ${zone} ec2 deregister-image --image-id %
  aws --region ${zone} ec2 copy-image --name ${NAME} --source-region us-west-2 --source-image-id ${IMAGE}
done
