#!/usr/bin/env bash

#this is a script to have /starphleet itself auto update
#bootstrap with
#curl -L https://raw.github.com/wballard/starphleet/master/provision/selfupdate | sudo bash

REMOTE="${STARPHLEET_REMOTE:-https://github.com/wballard/starphleet.git}"
LOCAL="/starphleet"
if [ -d "${LOCAL}" ]; then
  cd "${LOCAL}"
  #make sure we have the correct repository and branch
  ORIGIN_URL=`git config remote.origin.url`
  if [ "${ORIGIN_URL}" != "${REMOTE}" ]; then
    echo repository url differs, reclone needed
    cd ..
    rm -rf "${LOCAL}"
    git clone "${REMOTE}" "${local}"
    /starphleet/provision/system
    exit 0
  fi
  FETCH_RESULTS=`git fetch --all` || fatal fetch error
  HAS_CHANGES=`git diff HEAD...origin/master --raw`
  if [ "${HAS_CHANGES}x" = "x" ]; then
    sleep 10
  else
    git pull
    /starphleet/provision/system
    exit 0
  fi
else
  echo ${LOCAL} not found, initial clone needed
  git clone "${REMOTE}" "${LOCAL}"
  cd "${LOCAL}"
  git checkout master
  /starphleet/provision/system
  exit 0
fi
