#!/usr/bin/env bash

#this is a provisioning script, it is designed to be run under Vagrant
#as root, with the starphleet source tree at /starphleet

set -e

#get docker on
apt-get -y install --force-yes git curl apt-transport-https
apt-get -y install --force-yes software-properties-common
apt-get -y install --force-yes python g++ make git
curl http://get.docker.io/gpg | apt-key add -
echo "deb https://get.docker.io/ubuntu docker main" \
  > /etc/apt/sources.list.d/docker.list
add-apt-repository -y ppa:nginx/stable
add-apt-repository -y ppa:chris-lea/node.js
apt-get -y update
apt-get -y install --force-yes linux-image-extra-`uname -r`
apt-get -y install --force-yes lxc-docker
apt-get -y install --force-yes nginx
apt-get -y install --force-yes nodejs

#initial apt package has nginx running. lame.
/etc/init.d/nginx stop

#we will be using bash. period
mv /bin/sh /bin/shold
ln /bin/bash /bin/sh

/starphleet/provision/phleet
