#!/usr/bin/env bash
#######################################################################
## Author:          Benjamin Hudgens
## Date:            March 28, 2015
##
## Description:     Setup the necessary environment to install
##                  starphleet via vagrant
#######################################################################

# *********************
# Config
# *********************

ENVIRONMENT_FILE="${HOME}/.starphleet"
STARPHLEET_PRIVATE_KEY_FILE="${HOME}/.ssh/starphleet"
STARPHLEET_PUBLIC_KEY_FILE="${HOME}/.ssh/starphleet.pub"

# *********************
# Helpers
# *********************

function test_git() {
  SUCCESS=$(ssh -i ${1} git@github.com 2>&1 | grep "successfully authenticated")
}

function get_starphleet_branch() {
  read -p "Which branch for your Headquarters: " STARPHLEET_HEADQUARTERS_BRANCH
}

function headquarters_branch_help() {
cat <<EOF

  In development mode it is strongly recommended that you create a branch for
  yourself in the development headquarters git repo.

  The concensus is that it is rude to make changes to the main branch unless
  they are global and are intended for everyone to consume.

EOF
}

function key_help() {
cat <<EOF

  You must put a non-password protected key file here:

     ${STARPHLEET_PRIVATE_KEY_FILE}
     ${STARPHLEET_PUBLIC_KEY_FILE}


  To generate a new key you can try (do not enter a password - hit <enter>):

    ssh-keygen -b 1024 -t rsa -f ${HOME}/.ssh/starphleet


  Make sure your key is setup with GitHub.  Read here:

    https://help.github.com/articles/generating-ssh-keys/

EOF
}

# *********************
# Environment Setup
# *********************

# Check if the user has an environment file
[ -f "${ENVIRONMENT_FILE}" ] && source "${ENVIRONMENT_FILE}"

# Make sure a headquarters is set
if [ -z ${STARPHLEET_HEADQUARTERS} ]; then
  read -p "Please paste a starphleet headquarters: " STARPHLEET_HEADQUARTERS
  export STARPHLEET_HEADQUARTERS="${STARPHLEET_HEADQUARTERS}"
fi

# Require users to specify a branch explicitly so they remember not to trample
# on everyone else.  If their headquarters doesn't contain a branch .. prompt
if [ -z "$(echo ${STARPHLEET_HEADQUARTERS} | grep '#')" ]; then
  headquarters_branch_help
  get_starphleet_branch
fi
if [ ! -z "${STARPHLEET_HEADQUARTERS_BRANCH}" ]; then
  export STARPHLEET_HEADQUARTERS="${STARPHLEET_HEADQUARTERS}#${STARPHLEET_HEADQUARTERS_BRANCH}"
else
  exit 1
fi

# Graceful fallback if the user didn't setup the keys in their environment
if [ -z "${STARPHLEET_PRIVATE_KEY}" ] || [ -z "${STARPHLEET_PUBLIC_KEY}" ]; then
  # Test to make sure their key connects to github without issue
  [ -f "${STARPHLEET_PRIVATE_KEY_FILE}" ] && \
  [ -f "${STARPHLEET_PUBLIC_KEY_FILE}" ] && \
  test_git "${STARPHLEET_PRIVATE_KEY_FILE}"
  # If success - export the starphleet key
  if [ ! -z "${SUCCESS}" ]; then
    export STARPHLEET_PRIVATE_KEY="${STARPHLEET_PRIVATE_KEY_FILE}"
    export STARPHLEET_PUBLIC_KEY="${STARPHLEET_PUBLIC_KEY_FILE}"
  else
    # Starphleet key didn't work out - be a pal and try their default key
    test_git "${HOME}/.ssh/id_rsa"
    if [ ! -z "${SUCCESS}" ]; then
      export STARPHLEET_PRIVATE_KEY="${HOME}/.ssh/id_rsa"
      export STARPHLEET_PUBLIC_KEY="${HOME}/.ssh/id_rsa.pub"
    else
      # Sheesh - nothing is working
      key_help
      exit 1
    fi
  fi
fi

# *********************
# Main
# *********************

echo Starphleet HQ:     ${STARPHLEET_HEADQUARTERS}
echo SSH Public Key:    ${STARPHLEET_PUBLIC_KEY}
echo SSH Private Key:   ${STARPHLEET_PRIVATE_KEY}

vagrant up --provider vmware_fusion

# Give starphleet a few seconds to warm up before we go test things
echo "One moment while devmode initalizes.  This may take a while..."
sleep 10

# Now test how things are going
vagrant ssh -c "sudo starphleet-devmode-install-check"
