#!/usr/bin/env bash

#apt packages
read -r -d '' PACKAGES << FFF
autoconf
bind9-host
bison
build-essential
curl
daemontools
dnsutils
ed
git
imagemagick
iputils-tracepath
libcurl4-openssl-dev
libevent-dev
libglib2.0-dev
libjpeg-dev
libjpeg62
libpng12-0
libpng12-dev
libmagickcore-dev
libmagickwand-dev
libmysqlclient-dev
libpq-dev
libsqlite3-dev
libssl-dev
libssl0.9.8
libxml2-dev
libxslt-dev
mercurial
mysql-client
netcat-openbsd
openjdk-6-jdk
openjdk-6-jre-headless
openssh-client
openssh-server
python-dev
ruby1.9.1-dev
rubygems
socat
sqlite3
telnet
zlib1g-dev
bsdmainutils
FFF

sudo apt-get -y update
echo -n ${PACKAGES}  | tr ' ' '\n' | xargs -I % xargs sudo apt-get install -y --force-yes %

#ruby superstition
export HOME=/
sudo gem install bundler

