#!/usr/bin/env bash
REMOTE="${STARPHLEET_REMOTE:-https://github.com/wballard/starphleet.git}"
LOCAL="/var/starphleet/github"
apt-get update -y
apt-get install -y git
[ -d "${LOCAL}" ] || mkdir -p "${LOCAL}"
git clone  "${REMOTE}" "${LOCAL}"
cd "${LOCAL}"
./scripts/starphleet-install
