#!/bin/bash
set -e

app_root="${HOME}/app"
build_root="${app_root}"
cache_root="${BUILDPACK_CACHE_DIR:-${HOME}/cache/app}"
buildpack_root="${HOME}/build/buildpacks"

buildpacks=($buildpack_root/*)
selected_buildpack=

# start: heroku buildpack hack (some buildpacks create "temp" /app dir)
sudo bash -c "mkdir -p /app && chown ${STARPHLEET_APP_USER}:${STARPHLEET_APP_USER} /app"
# end: heroku buildpack hack

mkdir -p $cache_root
mkdir -p $build_root/.profile.d

# This is to get a custom buildpack. Probably should use profile.d though
[ -f "$app_root/.env" ] && . "$app_root/.env"

if [ -n "$BUILDPACK_URL" ]; then
  echo "       Fetching custom buildpack"
  buildpack="$buildpack_root/custom"
  rm -rf "$buildpack"
  #mod here to allow #branch syntax
  starphleet-git-synch "$BUILDPACK_URL" "$buildpack"
  selected_buildpack="$buildpack"
  buildpack_name=$($buildpack/bin/detect "$build_root") && selected_buildpack=$buildpack
else
  for buildpack in "${buildpacks[@]}"; do
    buildpack_name=$($buildpack/bin/detect "$build_root") && selected_buildpack=$buildpack && break
  done
fi

if [ -n "$selected_buildpack" ]; then
  echo "       $buildpack_name app detected"
else
  echo "       Unable to select a buildpack"
  exit 1
fi

# generate a random request id used by buildpack instrumentation
export REQUEST_ID=$(openssl rand -base64 32)

$selected_buildpack/bin/compile "$build_root" "$cache_root"

# start: heroku buildpack hack (some buildpacks create "temp" /app dir)
sudo rm -rf "/app"
sudo ln -s "${app_root}" "/app"
# end: heroku buildpack hack

echo "-----> Discovering process types"

$selected_buildpack/bin/release "$build_root" > "$build_root/.release"

if [[ -f "$build_root/Procfile" ]]; then
  types=$(ruby -e "require 'yaml';puts YAML.load_file('$build_root/Procfile').keys().join(', ')")
  echo "       Procfile declares types -> $types"
fi
default_types=$(ruby -e "require 'yaml';puts (YAML.load_file('$build_root/.release')['default_process_types'] || {}).keys().join(', ')")
[[ $default_types ]] && echo "       Default process types for $buildpack_name -> $default_types"

mkdir -p $build_root/.profile.d
ruby -e "require 'yaml';(YAML.load_file('$build_root/.release')['config_vars'] || {}).each{|k,v| puts \"#{k}=#{v}\"}" > $build_root/.profile.d/config_vars

cat << EOF > "${HOME}/start"
#!/bin/bash
export HOME=$build_root
for file in $build_root/.profile.d/*; do source \$file; done
env | sort
env | sudo bash -c "sort > \"\${STARPHLEET_ENV}\""
hash -r
cd $build_root
if [[ -f Procfile ]]; then
    ruby -e "require 'yaml';puts YAML.load_file('Procfile')['\$1']" | bash
else
    ruby -e "require 'yaml';puts (YAML.load_file('.release')['default_process_types'] || {})['\$1']" | bash
fi
EOF
chmod +x "${HOME}/start"

