#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools

## expose 0.1.0
### Usage:
###    expose <container> <container_port> <host_port>
### --help
###
### Export a port for a container via NAT through the host. Need some
### way to talk to the thing!
help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

CONTAINER_IP=$(lxc-ls --fancy | grep CN | awk '{print $3}')

iptables -t nat -A PREROUTING -m addrtype  --dst-type LOCAL  --jump STARPHLEET
iptables -t nat -A STARPHLEET -p tcp --dport ${host_port} ! --in-interface lxcbr0 --jump DNAT --to-destination ${CONTAINER_IP}:${container_port}
iptables -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j STARPHLEET
iptables -t nat -A POSTROUTING -s 10.0.3.0/24 -j MASQUERADE
