#! /usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
set -e

## headquarters 0.1.0
### Usage:
###    headquarters <url>
### --help
###
### Set the headquarters <url>. This is where the phleet will look for
### orders.
help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

echo ${url} > /var/starphleet/headquarters
