#! /usr/bin/env bash
# vi:ft=sh

# If we have a mount for syslog we move our syslog to the new mount
# and symlink back to the old
if [ -d /var/log/biglogs ] && [ ! -L /var/log/syslog ]; then
  # Being super defensive.  A condition exists where the symlink
  # prevented a start.  The bug was reported but not visually confirmed
  # so might tweak this if I ever run across the bug.
  stop rsyslog || true
  [ -f /var/log/syslog ] && mv /var/log/syslog /var/log/biglogs/syslog
  [ -f /var/log/syslog ] && rm /var/log/*syslog*
  [ -f /var/log/biglogs/syslog ] && [ ! -L /var/log/syslog ] && ln -s /var/log/biglogs/syslog /var/log/syslog
  touch /var/log/biglogs/syslog
  chown syslog:adm /var/log/syslog
  start rsyslog || true
fi
