#! /usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
set -e

## starphleet 0.1.0
### Usage:
###    phleet headquarters
###    phleet restart
###    phleet monitor
### --help
###
help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

echo ${url} > /var/starphleet/headquarters
