#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## publish-json 0.1.0
### Usage:
###    publish-json [--private=<private>] [--public=<public>] [--url=<url>]
### --help
###
### Specify the private (on container) and public (on host) ports, along with
### and URL stem to publish an HTTP service.
###
### Nothing is stopping you from creating a configuration that is confusing and
### redundant, specifically if you publish multiple services at the same URL.
### Just try not to.
###
### This is looking for environment variables
### CONTAINER
### CONTAINER_IP

help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

private=${private:-80}
public=${public:-80}
url=${url:-/}

echo ${private} ${public} ${url}

cat << EOF
{
  "containerIP": "${CONTAINER_IP}",
  "container": "${CONTAINER}",
  "hostPort": "${public}",
  "containerPort": "${private}",
  "url": "${url}"
}
EOF
