#!/usr/bin/env bash
#Given a repository directory, if it has changed versus the origin, mark
#it as changed with repository.changed

REPO_DIR=$1
#if you specify a directory, it had better exist
if [ ! -d "${REPO_DIR}" ]; then
  echo "${REPO_DIR} doesn't exist"
  exit 1
fi

cd "${REPO_DIR}"


FETCH_RESULTS=`git fetch --all `
if [ $? -ne 0 ]; then
  echo "fetch error in ${REPO_DIR}"
  echo "$FETCH_RESULTS"
  exit 4
fi

CURRENT_BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref HEAD`
CURRENT_SHA=`git log -n 1 --no-merges --pretty=format:%h`
ORIGIN_URL=`git config remote.origin.url`
HAS_CHANGES=`git diff HEAD...origin/${CURRENT_BRANCH} --raw`
if [ "${HAS_CHANGES}x" = "x" ]; then
  echo 'unchanged'
  exit 0
else
  git reset --hard origin/${CURRENT_BRANCH}
  echo 'changed'
  touch "${REPO_DIR}.changed"
fi

