#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools

## run 0.1.0
### Usage:
###    run <local_repository>
### --help
###
### Given a local repository that is Starphleet enabled, run it.
### This looks for a file ./Starphleet in the repository, and then inside that
### for:
###
### run script
### ... your script here...
### end script
###
### This script will be used to generate an upstart file, then used to run your
### service in a container.
help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

#use this to get the CONTAINER_NAME
makeBuilder

echo ${CONTAINER_NAME}
INSTANCE_NAME="${CONTAINER_NAME}-$$"
CONTAINER_ROOT=/var/lib/lxc/${INSTANCE_NAME}/rootfs

#create the 'run' script
EXTRACTOR='
  /run script/ { in_it = 1; next;}
  /end script/ {in_it = 0;}
  {if (in_it) print $0;}
'
RUNNER=${TMPDIR-/tmp}/$$
cat "${local_repository}/Starphleet" | awk "${EXTRACTOR}" - > ${RUNNER}
trap 'rm -rf ${RUNNER}' EXIT

#clone up a new container for this run, start it, and do a blocking run
#based on the script
lxc-clone -o "${CONTAINER_NAME}" -n "${INSTANCE_NAME}" -s
cp ${RUNNER} ${CONTAINER_ROOT}/.run

lxc-start --name ${INSTANCE_NAME} -d
lxc-wait --name ${INSTANCE_NAME} --state RUNNING
#this ends up with a fork here, so pay attention when this gets put
#in upstart to expect a fork
lxc-attach --name ${INSTANCE_NAME} -- bash /.run
lxc-stop --name ${INSTANCE_NAME}
lxc-wait --name ${INSTANCE_NAME} --state STOPPED
lxc-destroy --name ${INSTANCE_NAME}
