#! /usr/bin/env bash
### Usage:
###    starphleet-headquarters [<url>]
### --help
###
### Set the headquarters <url>. This is where the phleet will look for
### orders.
### The <url> can include a #branch on the end which will refer to that specific
### branch rather than default master.
###
### If <url> is not specified, this script will try to figure the headquarters
### for you by:
### * looking at EC2 metadata, including grabbing a private key
### * looking on all attached volumes for
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${DIR}/tools"
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"
set -e

if [ -z "${url}" ]; then
  if [ -f /starphleet/headquarters ]; then
    url=$(cat /starphleet/headquarters)
    if find /starphleet/private_keys/* > /dev/null ; then
      [ -d "${PRIVATE_KEYS}" ] && cp /starphleet/private_keys/* "${PRIVATE_KEYS}"
    fi
    if find /starphleet/public_keys/* > /dev/null ; then
      [ -d "${PUBLIC_KEYS}" ] && cp /starphleet/public_keys/* "${PUBLIC_KEYS}"
    fi
  fi
fi

if [ -n "${url}" ]; then
cat <<EOF > "${HEADQUARTERS_SOURCE}"
export HEADQUARTERS_REMOTE="${url}"
EOF
  info Headquarters set to ${url}
elif [ -f "${HEADQUARTERS_SOURCE}" ]; then
  :
else
  error no headquarters url provided
fi

