#!/usr/bin/env bash
### Usage:
###    starphleet-alias-publish <original_url> <as_new_url>
### --help
###
### Mount HTTP traffic at an additional location. This is useful to create
### a secondary mount, or to allocate an API-key style url mount point.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

set -e

original_url=$(echo "${original_url}/" | sed -e 's[//[/[g')
as_new_url=$(echo "${as_new_url}/" | sed -e 's[//[/[g')
PUBLISH_CONF="${NGINX_CONF}/published/$(urlencode \"${as_new_url}\").conf"

test ! -d "${NGINX_CONF}/published" && mkdir -p "${NGINX_CONF}/published"

cat << EOF > "${PUBLISH_CONF}"
location ${as_new_url} {
  include /var/starphleet/nginx/cors.conf;
  proxy_pass http://127.0.0.1${original_url};
  add_header X-ALIAS ${original_url};
  # WebSocket support (nginx 1.4)
  proxy_http_version 1.1;
  proxy_set_header Upgrade \$http_upgrade;
  proxy_set_header Connection "upgrade";
}
EOF

initctl list | grep 'starphleet_nginx' > /dev/null && (reload starphleet_nginx || start starphleet_nginx)

info aliased ${original_url} to ${as_new_url}
