#!/usr/bin/env bash
### Usage:
###    starphleet-lxc-backup <container_name> <backup_file>
### --help
###
### Make a single file package from an LXC image.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

cd "${LXC_ROOT}"
tar --numeric-owner -czf "${backup_file}" "${container_name}"
