#! /usr/bin/env bash
### Usage:
###    starphleet-headquarters <url>
### --help
###
### Set the headquarters <url>. This is where the phleet will look for
### orders.
### The <url> can include a #branch on the end which will refer to that specific
### branch rather than default master.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${DIR}/tools"
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"
set -e

cat <<EOF > /var/starphleet/.headquarters
export HEADQUARTERS_REMOTE="${url}"
export HEADQUARTERS_LOCAL="/var/starphleet/headquarters"
export CURRENT_ORDERS="/var/starphleet/current_orders"
export NGINX_CONF="/var/starphleet/nginx"
export ADMIRAL="admiral"
export ADMIRAL_HOME="/home/admiral"
if [ -s /var/starphleet/headquarters/.starphleet ]; then
  source /var/starphleet/headquarters/.starphleet
fi

EOF
cat "${DIR}/tools" >> /var/starphleet/.headquarters

info Headquarters is ${url}
