#!/usr/bin/env bash
### Usage:
###    starphleet-cleanup
### --help
###
### Call this to toss all starphleet state on shutdown
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

test -d "${STARPHLEET_ROOT}/node_modules" && rm -rf "${STARPHLEET_ROOT}/node_modules"
test -d ${STARPHLEET_TMP} && rm -rf ${STARPHLEET_TMP}/*
test -d "${STARPHLEET_TMP}" && rm -rf "${STARPHLEET_TMP}/*"
test -d "${ADMIRAL_HOME}/.npm" && rm -rf "${ADMIRAL_HOME}/.npm"

#deleting the headquarters makes sure we can get a version difference on start
#in order to kick off containers
test -d "${HEADQUARTERS_LOCAL}" && rm -rf "${HEADQUARTERS_LOCAL}"

#unpublish services from nginx
test -d "${NGINX_CONF}/published" && rm -rf "${NGINX_CONF}/published"
test -d "${NGINX_CONF}/published_bare" && rm -rf "${NGINX_CONF}/published_bare"
test -d "${NGINX_CONF}/published_bare" && rm -rf "${NGINX_CONF}/beta_groups"
