#!/usr/bin/env bash
### Usage:
###    starphleet-cleanup
### --help
###
### Call this to toss all starphleet state on shutdown
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

# if we are doing a starphleet-update, leave the lxc running
if [ ! -f "${STARPHLEET_ROOT}/.update" ]; then
  initctl emit starphleet_shutdown
  for container in $(lxc-ls | grep -e '\_CM[0-9]')
  do
    warn "need to destroy ${container}"
    starphleet-lxc-destroy ${container}
  done
fi
# now remove the update file, since it is no longer needed
rm -f "${STARPHLEET_ROOT}/.update"
#lose all service state on stop, putting things back to as if no
#services were published at all
test -d "${STARPHLEET_ROOT}/node_modules" && rm -rf "${STARPHLEET_ROOT}/node_modules"
test -d ${STARPHLEET_TMP} && rm -rf ${STARPHLEET_TMP}/*
test -d "${CURRENT_ORDERS}" && rm -rf "${CURRENT_ORDERS}"
test -d "${HEADQUARTERS_LOCAL}" && rm -rf "${HEADQUARTERS_LOCAL}"
test -d "${ADMIRAL_HOME}/.npm" && rm -rf "${ADMIRAL_HOME}/.npm"
