#!/usr/bin/env bash
### Usage:
###    starphleet-volumes
### --help
###
### Make sure we have a btrfs /var/lib/lxc to allow snapshots
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

if curl "http://169.254.169.254/latest/user-data/" --silent --connect-timeout 1 > /dev/null; then
  info setting up EC2 volumes
  #btrfs filesystem for images, this is mainly for the ec2 ephemeral
  #file system
  if df | grep /var/lib/lxc > /dev/null; then
    echo -n
  else
    #check for ephemeral device
    DEVICE=/dev/xvdb
    if [ -b ${DEVICE} ]; then
      echo device found, installing btrfs var
      #and make sure it is btrfs
      if mount | grep ${DEVICE} > /dev/null; then
        umount ${DEVICE}
      fi
      mkfs.btrfs --force ${DEVICE}
      #scrub away the mount point
      if [ -d /var/lib/lxc ]; then
        rm -rf /var/lib/lxc
      fi
      mkdir -p /var/lib/lxc
      mount ${DEVICE} /var/lib/lxc
    fi
  fi
else
  if mount | grep /dev/sda; then
    info device already mounted, not blowing myself away
  else
    if df | grep /var/lib/lxc > /dev/null; then
      echo -n
    else
      DEVICE=/dev/sda1
      parted --script -- ${DEVICE} mklabel gpt mkpart primary btrfs 1 -1
      mkfs.btrfs --force ${DEVICE}
      mkdir -p /var/lib/lxc
      mount ${DEVICE} /var/lib/lxc
    fi
  fi
fi
