#!/usr/bin/env bash
### Usage:
###    starphleet-run-web <order> <container>
### --help
###
### Run a container as a Heroku build pack web start
### * tee through to logger to support syslog
### * capture both stderr and stdout with syslog logging
###
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

#stderr too!
exec 2>&1
#stdout to a pipe for logger
exec > >(logger --stderr -t "${order}")

set -e
lxc-attach --name ${container} -- sudo -H -u ${STARPHLEET_APP_USER} bash -c "setsid ~/start web"
