#!/usr/bin/env bash
### Usage:
###    starphleet-addresses
### --help
###
### Print out the physical network interface IP addresses, and be smart
### enough to ignore the lxc and loopback interfaces
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

#ok, by smart enough, this isn't very smart
for interface in eth0 eth1 em1 em2
do
  ifconfig $interface 2>/dev/null\
    | grep 'inet addr' \
    | awk '{ print $2; }' \
    | sed -e 's/addr://'
done
