#!/usr/bin/env bash
### Usage:
###    starphleet-destroy-lxc <name>
### --help
###
### This is a more thorough destroy that will:
### * make sure the container is stopped
### * destroy the container
### * make sure the root file system is really gone
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

lxc-stop --name ${name}
while lxc-ls | grep "^${name}" > /dev/null; do
  lxc-destroy --name "${name}"
  warn trying again...
  sleep 1
done

