#!/usr/bin/env bash
### Usage:
###    starphleet-lxc-stop <container_name>
### --help
###
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

while lxc-info -n "${container_name}" | grep RUNNING; do
  info stopping ${container_name}
  lxc-stop --nowait --name ${container_name} 2>&1
  sleep 1
done
