#!/usr/bin/env bash
## starphleet-wait-network 0.1.0
### Usage:
###    starphleet-wait-network
### --help
###
### Wait until it is obvious there is an address lease. This is a
### script generating script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

cat << EOF
#need to wait until the network is up
until ifconfig | grep 'inet addr' | grep --invert '127.0.0.1'
do
  echo waiting for network
  sleep 1
done
EOF
