#!/usr/bin/env bash

  #btrfs filesystem for images, this is mainly for the ec2 ephemeral
  #file system
  echo starting starphleet
  if df | grep /var/lib/lxc > /dev/null; then
    echo -n
  else
    #check for ephemeral device
    DEVICE=/dev/xvdb
    if [ -b ${DEVICE} ]; then
      echo device found, installing btrfs var
      #and make sure it is btrfs
      if mount | grep ${DEVICE} > /dev/null; then
        umount ${DEVICE}
      fi
      mkfs.btrfs ${DEVICE}
      #scrub away the mount point
      if [ -d /var/lib/lxc ]; then
        rm -rf /var/lib/lxc
      fi
      mkdir -p /var/lib/lxc
      mount ${DEVICE} /var/lib/lxc
    fi
  fi
