#!/usr/bin/env bash
### Usage:
###    starphleet-ready <container_name> <container_port> <url>
### --help
###
### Check if a container is ready by looking for a successful http return.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"
trace "$(basename "$(test -L "$0" && readlink "$0" || echo "$0")") : $*"

PORT=${container_port:-${PORT}}
URL=${url:-/}
IP_ADDRESS=$(lxc-ls --fancy | grep "^${container_name}[[:space:]]" | awk '{ print $3; }')

TEST_PASSED=false
for c in {1..180}; do
  TEST_GET="http://${IP_ADDRESS}:${PORT}${URL}"
  TEST_COMMAND="curl -X GET -o /dev/null -s -w %{response_code} ${TEST_GET}"
  RESULT=`${TEST_COMMAND}`
  if [ ${RESULT} == "200" ]; then
    TEST_PASSED=true
    break;
  fi
  # we'll read a timeout configuration from our environment, and if its not
  # specified, we'll just default to the actual controlling loop (for loop)
  # boundary.  So this will allow you to specify some value other other than
  # the default (180) without ever surpassing the default of 180.
  # since our caller sources the orders file, this can be added to your orders
  # for a specific service
  [ $c -gt ${HEALTHCHECK_TIMEOUT:-180} ] && break
  sleep 1;
done

if [ "${TEST_PASSED}" != "true" ]; then
  error "service was not ready at ${IP_ADDRESS}:${PORT}"
  exit 1
fi

info "${container_name} is ready"
