#!/usr/bin/env bash
### Usage:
###    starphleet-lxc-destroy <container_name>
### --help
###
### This is a more thorough destroy that will:
### * make sure the container is stopped
### * destroy the container
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

starphleet-lxc-stop "${container_name}"

while lxc-ls | grep "^${container_name}$"; do
  info destroying ${container_name}
  lxc-destroy --name "${container_name}" 2>&1
  sleep 1
done
