#! /usr/bin/env bash
### Usage:
###    starphleet-headquarters [<url>]
### --help
###
### Set the headquarters <url>. This is where the phleet will look for
### orders.
### The <url> can include a #branch on the end which will refer to that specific
### branch rather than default master.
###
### If <url> is not specified, this script will try to figure the headquarters
### for you by:
### * looking at EC2 metadata, including grabbing a private key
### * looking on all attached volumes for
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${DIR}/tools"
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"
set -e

if [ -n "${url}" ]; then
  echo export HEADQUARTERS_REMOTE="${url}" > "${HEADQUARTERS_SOURCE}"
  info Headquarters set to ${url}
elif [ -f "${HEADQUARTERS_SOURCE}" ]; then
  info Headquarters is $(cat ${HEADQUARTERS_SOURCE})
else
  error no headquarters url provided
fi

