#!/usr/bin/env bash
### Usage:
###    starphleet-base-script
### --help
###
### Generate the a script to create a base image with buildpack support
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
help=$(grep "^### " "$0" | cut -c 5-)
source ${DIR}/tools
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

cat << "EOF"
read -r -d '' PACKAGES << FFF
autoconf
bind9-host
bison
build-essential
curl
daemontools
dnsutils
ed
git
imagemagick
iputils-tracepath
libcurl4-openssl-dev
libevent-dev
libglib2.0-dev
libjpeg-dev
libjpeg62
libpng12-0
libpng12-dev
libmagickcore-dev
libmagickwand-dev
libmysqlclient-dev
libpq-dev
libsqlite3-dev
libssl-dev
libssl0.9.8
libxml2-dev
libxslt-dev
mercurial
mysql-client
netcat-openbsd
openjdk-6-jdk
openjdk-6-jre-headless
openssh-client
openssh-server
python-dev
ruby1.9.1-dev
rubygems
socat
sqlite3
telnet
zlib1g-dev
FFF

EOF

cat << "EOF"
read -r -d '' BUILDPACKS << FFF
https://github.com/heroku/heroku-buildpack-ruby.git
https://github.com/wballard/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-java.git
https://github.com/heroku/heroku-buildpack-play.git
https://github.com/heroku/heroku-buildpack-python.git
https://github.com/heroku/heroku-buildpack-php.git
https://github.com/heroku/heroku-buildpack-clojure.git
https://github.com/kr/heroku-buildpack-go.git
https://github.com/miyagawa/heroku-buildpack-perl.git
https://github.com/heroku/heroku-buildpack-scala
https://github.com/igrigorik/heroku-buildpack-dart.git
https://github.com/rhy-jot/buildpack-nginx.git
https://github.com/Kloadut/heroku-buildpack-static-apache.git
FFF

EOF

cat << "EOF"

  #here we go, making a buildpack ready system
  apt-get install -y --force-yes software-properties-common
  add-apt-repository -y ppa:chris-lea/node.js
  apt-get -y update
  echo -n ${PACKAGES}  | tr ' ' '\n' | xargs -I % xargs apt-get install -y --force-yes %
  apt-get clean

  #load on all the buildpacks
  mkdir -p /build/buildpacks
  cd /build/buildpacks
  echo -n ${BUILDPACKS}  | tr ' ' '\n' | xargs -I % git clone --depth 1 %

  #ruby superstition
  export HOME=/
  gem install bundler
  cd /build/buildpacks/heroku-buildpack-ruby && bundle install

EOF

cat << "EOF"
    # adding in the Yhat stuff
    echo "-----> Building Yhat scientific environment"

    function install_rpkg() {
      pkg="$1"
      cmd="r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);"
      Rscript -e "${cmd}install.packages('${pkg}')"
    }
    
    # start Yhat build
    apt-get update
    apt-get -y install software-properties-common python g++ make git
    apt-get -y install python-software-properties
    apt-get update
    
    # python
    apt-get -y install python-setuptools
    apt-get -y install python-pip
    apt-get -y install python-dev build-essential
    apt-get install -y python-numpy
    apt-get install -y python-scipy
    pip install scikit-learn
    apt-get install -y python-pandas
    easy_install statsmodels
    pip install -U patsy
    pip install -U yhat
    
    # r stuff
    apt-get -y install r-base
    pip install rpy2
    apt-get -y install libcurl4-openssl-dev
    #setup R configs
    install_rpkg "yhatr"
    install_rpkg "ggplot2"
    install_rpkg "plyr"
    install_rpkg "reshape2"
    install_rpkg "forecast"
    install_rpkg "stringr"
    install_rpkg "lubridate"
    install_rpkg "randomForest"
    install_rpkg "rpart"
    install_rpkg "e1071"
    install_rpkg "kknn"

EOF


