#!/usr/bin/env bash
### Usage:
###    starphleet-lxc-destroy <container_name>
### --help
###
### This is a more thorough destroy that will:
### * make sure the container is stopped
### * destroy the container
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

starphleet-lxc-stop "${container_name}"

while lxc-ls | grep "^${container_name}$"; do
  info destroying ${container_name}
  lxc-destroy --name "${container_name}" 2>&1
done

# Destroy command from LXC sometimes misses getting rid of its
# trash so lets help just in case.
lxc_container_path="/var/lib/lxc/${container_name}"

[ -n "${container_name}" ] \
  && [ -d "${lxc_container_path}" ] \
  && rm -rf "${lxc_container_path}" \
  || true

rm /var/lib/lxc/${container_name}.serve_only_override || true
