#!/usr/bin/env bash
### Usage:
###    starphleet-lxc-ssh ORDERNAME [COMMAND ...]
### --help
###
###   "Runs ssh to connect to the given container"
###
###   "Arguments:"
###   "NAME    : name of the original starphleet order.  Replaced with the IP address of the container."
###   "COMMAND : optional command to pass to ssh"
###
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"
trace "$(basename "$(test -L "$0" && readlink "$0" || echo "$0")") : $*"
set -e

get_ip(){
  for name in $(sudo lxc-ls --running | grep --extended-regexp "${ENCODED_ORDER}-")
    do
      ip=$(sudo lxc-ls --fancy -F ipv4 $name | tail -1)
      if [ -n  ${ip} ]; then
        echo "$ip"
        break;
      fi
  done
}

do_ssh(){

    # Use get_ip to wait for container's network to be up
    # and to obtain the ip address, then we can ssh to the lxc.
    TRIES=60
    FAILED=1

    # Repeatedly try to connect over SSH until we either succeed
    # or time out.
    for i in $(seq 1 $TRIES); do
        IP_ADDRESS=$(get_ip $ENCODED_ORDER)
        if [ -z "$IP_ADDRESS" ]; then
            sleep 1
            continue
        fi

        # Iterate through all the addresses (if multiple)
        for ip in $IP_ADDRESS; do
            ssh -o StrictHostKeyChecking=no \
                -o UserKnownHostsFile=/dev/null \
                $SSH_OPTS \
                admiral@$IP_ADDRESS "$@"
            if [ ! 255 -eq $? ]; then
                # If ssh returns 255 then its connection failed.
                # Anything else is either success (status 0) or a
                # failure from whatever we ran over the SSH connection.
                # In those cases we want to stop looping, so we break
                # here

                FAILED=0
                break;
            fi
        done

        if [ "$FAILED" = "0" ]; then
            break
        fi
        sleep 1
    done

    if [ "$FAILED" = "1" ]; then
        echo "could not get IP address - aborting." >&2
    fi
}

ENCODED_ORDER=$(urlencode "$1")
shift
SSH_OPTS="-t"
do_ssh "$@"
