#!/usr/bin/env bash
### Usage:
###    starphleet-wait-network
###
### Wait until it is obvious there is an address lease.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#need to wait until the network is up
echo waiting for network
until ifconfig | grep 'inet addr' | grep --invert '127.0.0.1' > /dev/null
do
  sleep 0.1
done
