#!/usr/bin/env bash
### Usage:
###    starphleet-logs [<service_name>]
### --help
###
### Tail the logs for starphleet services.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

if [ -n "${service_name}" ]; then
  cat /var/log/upstart/starphleet_serve_order-service-${service_name}-*.log
  tail -F --lines 0 /var/log/upstart/starphleet_serve_order-service-${service_name}-*.log
else
  tail -F /var/log/upstart/*starphleet*.log
fi
