#!/usr/bin/env bash
### Usage:
###    starphleet-destroy-lxc <name>
### --help
###
### This is a more thorough destroy that will:
### * make sure the container is stopped
### * destroy the container
### * make sure the root file system is really gone
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

test -f /tmp/wait-lock || touch /tmp/wait-lock
flock /tmp/wait-lock --command "lxc-stop --name ${name}"
flock /tmp/wait-lock --command "lxc-wait --name ${name} --state STOPPED --timeout 60"
until lxc-destroy --name "${CONTAINER_NAME}"; do
  warn trying again...
  sleep 1
done

