#!/usr/bin/env bash
### Usage:
###    starphleet-unpublish <public_url>
### --help
###
### Remove HTTP traffic from a public url.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

set -e
PUBLISH_CONF="${NGINX_CONF}/published/$(urlencode \"${public_url}\").conf"
rm "${PUBLISH_CONF}"
