#!/usr/bin/env bash
### Usage:
###    starphleet-ready <container_group> <container_port> <url>
### --help
###
### Check if a container is ready by looking for a successful http return.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"
trace "$(basename "$(test -L "$0" && readlink "$0" || echo "$0")") : $*"

PORT=${container_port:-${PORT}}
URL=${url:-/}

for IP_ADDRESS in $(lxc-ls --fancy | grep "^${container_group}" | awk '{ print $3; }'); do
  TEST_PASSED=false
  for c in {1..100}; do
    TEST_GET="http://${IP_ADDRESS}:${PORT}${URL}"
    TEST_COMMAND="curl -X GET -o /dev/null -s -w %{response_code} ${TEST_GET}"
    RESULT=`${TEST_COMMAND}`
    if [ -n "${DEBUG}" ]; then
      echo ${RESULT}
    fi
    if [ ${RESULT} == "200" ]; then
      TEST_PASSED=true
      break;
    fi
    sleep .2;
  done

  if [ -n "${DEBUG}" ]; then
    echo ${RESULT}
  fi
  if [ ! TEST_PASSED ]; then
    exit 1
  fi
done
exit 0;
