#!/usr/bin/env bash
### Usage:
###    starphleet-ldap-servers
### --help
###
### Configure named LDAP server entries that can be referenced by individual
### services.
###
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"
trace "$(basename "$(test -L "$0" && readlink "$0" || echo "$0")") : $*"
set -e

[ -d "${NGINX_CONF}/ldap_servers" ]  && rm -rf "${NGINX_CONF}/ldap_servers"
mkdir -p "${NGINX_CONF}/ldap_servers"

for LDAP_SERVER in $(find "${HEADQUARTERS_LOCAL}/ldap_servers" -type f)
do
  info ${LDAP_SERVER}
  source ${LDAP_SERVER}
cat << EOF > "${NGINX_CONF}/ldap_servers/$(basename ${LDAP_SERVER}).conf"
  ldap_server $(basename ${LDAP_SERVER}) {
   url ${LDAP_URL};
   binddn "${LDAP_USER}";
   binddn_passwd "${LDAP_PASSWORD}";
   group_attribute uniquemember;
   group_attribute_is_dn on;
   connections 8;
   require valid_user;
  }
EOF
done
