#!/usr/bin/env bash
### Usage:
###    starphleet-push-serve <container_name>
### --help
###
### Serve traffic for a container created via git push.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

set -e

#we aren't doing a healthcheck, this is just gonna publish
CONTAINER_ROOT=/var/lib/lxc/${container_name}/rootfs
#sourcing here to get variables, in particular $PORT
test -f "${CONTAINER_ROOT}/.orders" && source "${CONTAINER_ROOT}/.orders"
test -f "${CONTAINER_ROOT}/.starphleet" && source "${CONTAINER_ROOT}/.starphleet"

#this is counting on the fact that the container is already running

#publish before we start, this is a bit different than how things work
#when running under upstart -- no need for a rolling upgrade
info PORT is ${PORT}
starphleet-publish "${container_name}" ${PORT} "/${container_name}"

lxc-attach --name ${container_name} -- /web

function exit() {
  starphleet-unpublish "${container_name}"
}

trap 'exit' EXIT
