#!/usr/bin/env bash
### Usage:
###    starphleet-healthcheck <name> <order> <url>
### --help
###
### Check if a container is ready by looking for a successful http return.

name=$1
order=$2
url=$3
CURRENT_ORDERS=${CURRENT_ORDERS:-"/var/starphleet/current_orders"}
STATUS_FILE="${CURRENT_ORDERS}/${order}/.starphleetstatus.${name}"

HEALTHCHECK_TIMEOUT=${HEALTHCHECK_TIMEOUT:-30}

[ -f "${STATUS_FILE}.ip" ] && CONTAINER_IP=$(cat "${STATUS_FILE}.ip")
[ -f "${STATUS_FILE}.port" ] && CONTAINER_PORT=$(cat "${STATUS_FILE}.port")
URL=${url:-/}

if [ -z ${CONTAINER_IP} ] || [ -z ${CONTAINER_PORT} ]; then
  echo "Cannot find container ip address or port"
  exit 1
fi

TEST_GET="http://${CONTAINER_IP}:${CONTAINER_PORT}${URL}"
TEST_COMMAND="curl -X GET --connect-timeout ${HEALTHCHECK_TIMEOUT} -m ${HEALTHCHECK_TIMEOUT} -o /dev/null -s -w %{response_code} ${TEST_GET}"
RESULT=`${TEST_COMMAND}`
if [ ${RESULT} == "200" ] \
|| [ ${RESULT} == "301" ] \
|| [ ${RESULT} == "302" ] \
|| [ ${RESULT} == "401" ]; then
  exit 0
fi

echo Failed Healthcheck - ${TEST_GET}
exit 1
