#!/usr/bin/env bash
### Usage:
###    starphleet-run-web <order> <container>
### --help
###
### Run a container as a Heroku build pack web start
### * tee through to logger to support syslog
### * capture both stderr and stdout with syslog logging
###
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"
trace "$(basename "$(test -L "$0" && readlink "$0" || echo "$0")") : $*"

set -e
2>&1 lxc-attach --name ${container} -- sudo -H -u ${STARPHLEET_APP_USER} bash -c "setsid ~/start web" | logger --stderr -t "${order}"
