#!/usr/bin/env bash
### Usage:
###    starphleet-lxc-wait <name> <state>
### --help
###
### Wait until it is obvious there is an address lease. This is a
### script generating script.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

test -f /tmp/wait-lock || touch /tmp/wait-lock
flock /tmp/wait-lock --command "lxc-wait --name ${name} --state ${state} --timeout 30"
