#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
set -e

#This is the buildpack runner, this is really only useful to run
#on a container as part of a build

app_root=/app
cache_root=/cache
buildpack_root=/var/starphleet/buildpacks

buildpacks=($buildpack_root/*)
selected_buildpack=

mkdir -p $cache_root

# This is to get a custom buildpack. Probably should use profile.d though
test -f "$app_root/.env" && . "$app_root/.env"

if [ -n "$BUILDPACK_URL" ]; then
  echo "       Fetching custom buildpack"
  buildpack="$buildpack_root/custom"
  rm -rf "$buildpack"
  git clone --depth=1 "$BUILDPACK_URL" "$buildpack"
  selected_buildpack="$buildpack"
  buildpack_name=$($buildpack/bin/detect "$app_root") && selected_buildpack=$buildpack
else
  for buildpack in "${buildpacks[@]}"; do
    buildpack_name=$($buildpack/bin/detect "$app_root") && selected_buildpack=$buildpack && break
  done
fi

if [ -n "$selected_buildpack" ]; then
  echo "       $buildpack_name app detected"
else
  echo "       Unable to select a buildpack"
  exit 1
fi

$selected_buildpack/bin/compile "$app_root" "$cache_root"

echo "-----> Discovering process types"
$selected_buildpack/bin/release "$app_root" "$cache_root" > "$app_root/.release"

if [[ -f "$app_root/Procfile" ]]; then
  types=$(ruby -e "require 'yaml';puts YAML.load_file('$app_root/Procfile').keys().join(', ')")
  echo "       Procfile declares types -> $types"
fi
default_types=$(ruby -e "require 'yaml';puts (YAML.load_file('$app_root/.release')['default_process_types'] || {}).keys().join(', ')")
[[ $default_types ]] && echo "       Default process types for $buildpack_name -> $default_types"

cat > /exec <<EOF
#!/bin/bash
export HOME=/app
for file in $app_root/.profile.d/*; do source \$file; done
hash -r
cd $app_root
"\$@"
EOF
chmod +x /exec

cat > /start <<EOF
#!/bin/bash
export HOME=/app
[ -f "$app_root/.env" ] && . "$app_root/.env"
for file in $app_root/.profile.d/*; do source \$file; done
[ -f /.orders ] && source /.orders
[ -f /.starphleet ] && source /.starphleet
hash -r
echo \$\$ > /.pid
cd $app_root
if [[ -f Procfile ]]; then
    ruby -e "require 'yaml';puts YAML.load_file('Procfile')['\$1']" | bash
else
    ruby -e "require 'yaml';puts (YAML.load_file('.release')['default_process_types'] || {})['\$1']" | bash
fi
EOF
chmod +x /start

