#!/usr/bin/env bash
### Usage:
###    starphleet-dns-offline
###
### Call this to bring the status check endpoint online for Route 53
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/tools
help=$(grep "^### " "$0" | cut -c 5-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

# Make sure the published folder exists
[ -f ${NGINX_STATUS_CONFIG_PATH} ] || mkdir -p ${NGINX_STATUS_CONFIG_PATH}

# Generate the endpoint
echo "location ${NGINX_STATUS_URL} {     " > ${NGINX_STATUS_CONFIG_FILE}
echo '   return 200 "Ok";                ' >> ${NGINX_STATUS_CONFIG_FILE}
echo '}                                  ' >> ${NGINX_STATUS_CONFIG_FILE}

## Will B wants HUP
NGINX_PID=$(cat ${NGINX_PID_FILE})

## HUP NGinx
if [ -n ${NGINX_PID} ]; then
  kill -HUP ${NGINX_PID}
fi

# Output something to the user
echo "The hostcheck endpoint for this host has been enabled"
