#!/usr/bin/env bash

find /var/starphleet/containers/*.cid \
| sed s%/var/starphleet/containers/%% \
| sed s%.cid$%% \
| xargs -I % stop starphleet_serve service=%

find /var/starphleet/headquarters.git/ \
| grep 'orders$' \
| xargs -I % stop starphleet_autodeploy order=%

rm -rf /var/starphleet/headquarters.git
rm -rf /var/starphleet/containers
rm -rf /var/starphleet/current_orders
rm /var/starphleet/servers.conf
