#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## wait-network 0.1.0
### Usage:
###    wait-network
### --help
###
### Wait until it is obvious there is an address lease.
help=$(grep "^### " "$0" | cut -c 5-)
version=$(grep "^## "  "$0" | cut -c 4-)
eval "$(${DIR}/docopts -h "$help" -V "$version" : "$@")"

#need to wait until the network is up
until ifconfig | grep 'inet addr' | grep --invert '127.0.0.1'
do
  echo waiting for network
  sleep 1
done
